### ISSUE TITLE
怎么实现一个两列等高布局？一列定宽，一列自适应

### ISSUE THREAD

**Issue by wangyuan0108** [wangyuan0108/blog#23]

**Comment by yafully** [comment]
1:父：display table+display 子a：table cell 
2:html,body{height:100%}父容器position:relative;height:100%;子容器a:position:relative;height:100%;float:left;width:200px;
3:父：position:relative;height:100%；width:100%;padding-left:200px;子a:position:absolute;left:-200px;width:200px;子:b position:relative;height:100%;
4:html5 column

**Comment by wxxwtt** [comment]
/* 方法一 推荐*/
		.father {
			height: 200px;
			display: flex;
		}

		.left {

			width: 200px;
			background-color: rgb(165, 214, 225);
		}

		.right {
			flex: 1;
			background-color: rgb(176, 176, 176);
		}

		/* 方法二 */
		.father {
			height: 200px;
			position: relative;
		}

		.left {
			position: absolute;
			left: 0;
			top: 0;
			width: 200px;
			height: 200px;
			background-color: rgb(165, 214, 225);
		}

		.right {
			margin-left: 200px;
			width: 100%;
			height: 200px;
			background-color: rgb(176, 176, 176);
		}


		/* 方法三 */
		.father {
			height: 200px;
		}

		.left {
			float: left;
			height: 200px;
			width: 200px;
			background-color: rgb(165, 214, 225);
		}

		.right {
			margin-left: 200px;
			width: 100%;
			height: 200px;
			background-color: rgb(176, 176, 176);
		}

**Comment by wangyuan0108** [comment]
```css
section {
    width:100%;
    display: table;
}
article  {
    display: table-cell;
}
.left {
    height: 100px;
    background: red;
}
.right {
    background: black;
}
```
