### ISSUE TITLE
使用iconfont图标，在有文字的情况下出现竖直方向对不齐，文字偏下的处理方法。

### ISSUE THREAD

**Issue by wangyuan0108** [wangyuan0108/blog#87]
```css
.iconfont {
    position: relative;
    top:0.1rem;
}
```
备注：top的值可以根据实际情况进行改变
